export const classificationModels = {
  ada_boost_classifier: {
    estimator: { type: ["estimator", "None"], default: null },
    n_estimators: { type: "int", default: 50, min: 1 },
    learning_rate: { type: "float", default: 1.0, min: 0 },
    algorithm: { type: "str", default: "deprecated" },
    random_state: { type: ["int", "None"], default: null },
  },
  decision_tree_classifier: {
    criterion: { type: ["gini", "entropy", "log_loss"], default: "gini" },
    splitter: { type: ["best", "random"], default: "best" },
    max_depth: { type: ["int", "None"], default: null, min: 1 },
    min_samples_split: { type: "int", default: 2, min: 2 },
    min_samples_leaf: { type: "int", default: 1, min: 1 },
    min_weight_fraction_leaf: { type: "float", default: 0.0, min: 0 },
    max_features: { type: ["auto", "sqrt", "log2", "int", "float", "None"], default: null },
    random_state: { type: ["int", "None"], default: null },
    max_leaf_nodes: { type: ["int", "None"], default: null, min: 2 },
    min_impurity_decrease: { type: "float", default: 0.0, min: 0 },
    class_weight: { type: ["dict", "str", "None"], default: null },
    ccp_alpha: { type: "float", default: 0.0, min: 0 },
    monotonic_cst: { type: ["array", "None"], default: null },
  },
  gradient_boosting_classifier: {
    loss: { type: ["log_loss", "exponential"], default: "log_loss" },
    learning_rate: { type: "float", default: 0.1, min: 0 },
    n_estimators: { type: "int", default: 100, min: 1 },
    subsample: { type: "float", default: 1.0, min: 0, max: 1.0 },
    criterion: { type: ["friedman_mse", "squared_error"], default: "friedman_mse" },
    min_samples_split: { type: "int", default: 2, min: 2 },
    min_samples_leaf: { type: "int", default: 1, min: 1 },
    min_weight_fraction_leaf: { type: "float", default: 0.0, min: 0 },
    max_depth: { type: "int", default: 3, min: 1 },
    min_impurity_decrease: { type: "float", default: 0.0, min: 0 },
    init: { type: ["estimator", "None"], default: null },
    random_state: { type: ["int", "None"], default: null },
    max_features: { type: ["auto", "sqrt", "log2", "int", "float", "None"], default: null },
    verbose: { type: "int", default: 0, min: 0 },
    max_leaf_nodes: { type: ["int", "None"], default: null, min: 2 },
    warm_start: { type: "bool", default: false },
    validation_fraction: { type: "float", default: 0.1, min: 0, max: 1.0 },
    n_iter_no_change: { type: ["int", "None"], default: null, min: 1 },
    tol: { type: "float", default: 0.0001, min: 0 },
    ccp_alpha: { type: "float", default: 0.0, min: 0 },
  },
  k_nearest_neighbors_classifier: {
    n_neighbors: { type: "int", default: 5, min: 1 },
    weights: { type: ["uniform", "distance"], default: "uniform" },
    algorithm: { type: ["auto", "ball_tree", "kd_tree", "brute"], default: "auto" },
    leaf_size: { type: "int", default: 30, min: 1 },
    p: { type: "int", default: 2, min: 1 },
    metric: { type: ["minkowski", "euclidean", "manhattan", "chebyshev"], default: "minkowski" },
    metric_params: { type: ["dict", "None"], default: null },
    n_jobs: { type: ["int", "None"], default: null },
  },
  logistic_regression: {
    penalty: { type: ["l1", "l2", "elasticnet", "None"], default: "l2" },
    dual: { type: "bool", default: false },
    tol: { type: "float", default: 0.0001, min: 0 },
    C: { type: "float", default: 1.0, min: 0 },
    fit_intercept: { type: "bool", default: true },
    intercept_scaling: { type: "float", default: 1, min: 0 },
    class_weight: { type: ["dict", "str", "None"], default: null },
    random_state: { type: ["int", "None"], default: null },
    solver: { type: ["liblinear", "lbfgs", "newton-cg", "sag", "saga"], default: "liblinear" },
    max_iter: { type: "int", default: 100, min: 1 },
    multi_class: { type: ["auto", "ovr", "multinomial"], default: "ovr" },
    verbose: { type: "int", default: 0, min: 0 },
  },
  random_forest_classifier: {
    n_estimators: { type: "int", default: 100, min: 1 },
    criterion: { type: ["gini", "entropy", "log_loss"], default: "gini" },
    max_depth: { type: ["int", "None"], default: null, min: 1 },
    min_samples_split: { type: "int", default: 2, min: 2 },
    min_samples_leaf: { type: "int", default: 1, min: 1 },
    min_weight_fraction_leaf: { type: "float", default: 0.0, min: 0 },
    max_features: { type: ["auto", "sqrt", "log2", "int", "float", "None"], default: "sqrt" },
    max_leaf_nodes: { type: ["int", "None"], default: null, min: 2 },
    min_impurity_decrease: { type: "float", default: 0.0, min: 0 },
    bootstrap: { type: "bool", default: true },
    oob_score: { type: "bool", default: false },
    n_jobs: { type: ["int", "None"], default: null },
    random_state: { type: ["int", "None"], default: null },
    verbose: { type: "int", default: 0, min: 0 },
    warm_start: { type: "bool", default: false },
    class_weight: { type: ["dict", "str", "None"], default: null },
    ccp_alpha: { type: "float", default: 0.0, min: 0 },
    max_samples: { type: ["int", "float", "None"], default: null, min: 1 },
    monotonic_cst: { type: ["array", "None"], default: null },
  },
  support_vector_classifier: {
    C: { type: "float", default: 1.0, min: 0 },
    kernel: { type: ["linear", "poly", "rbf", "sigmoid"], default: "rbf" },
    degree: { type: "int", default: 3, min: 1 },
    gamma: { type: ["scale", "auto", "float"], default: "scale" },
    coef0: { type: "float", default: 0.0, min: 0 },
    shrinking: { type: "bool", default: true },
    probability: { type: "bool", default: false },
    tol: { type: "float", default: 0.001, min: 0 },
    cache_size: { type: "float", default: 200, min: 0 },
    class_weight: { type: ["dict", "str", "None"], default: null },
    verbose: { type: "bool", default: false },
    max_iter: { type: "int", default: -1 },
    decision_function_shape: { type: ["ovo", "ovr"], default: "ovr" },
    break_ties: { type: "bool", default: false },
    random_state: { type: ["int", "None"], default: null },
  },
};