export const clusteringModels = {
  agglomerative_clustering: {
    n_clusters: 2,
    metric: "euclidean",
    memory: null,
    connectivity: null,
    compute_full_tree: "auto",
    linkage: "ward",
    distance_threshold: null,
    compute_distances: false,
  },
  birch_clustering: {
    threshold: 0.5,
    branching_factor: 50,
    n_clusters: 3,
    compute_labels: true,
    copy: true,
  },
  dbscan: {
    eps: 0.5,
    min_samples: 5,
    metric: "euclidean",
    metric_params: null,
    algorithm: "auto",
    leaf_size: 30,
    p: null,
    n_jobs: null,
  },
  k_means_clustering: {
    n_clusters: 8,
    init: "k-means++",
    n_init: "auto",
    max_iter: 300,
    tol: 0.0001,
    verbose: 0,
    random_state: null,
    copy_x: true,
    algorithm: "lloyd",
  },
  mean_shift_clustering: {
    bandwidth: null,
    seeds: null,
    bin_seeding: false,
    min_bin_freq: 1,
    cluster_all: true,
    n_jobs: null,
    max_iter: 300,
  },
  mini_batch_kmeans: {
    n_clusters: 8,
    init: "k-means++",
    max_iter: 100,
    batch_size: 1024,
    verbose: 0,
    compute_labels: true,
    random_state: null,
    tol: 0.0,
    max_no_improvement: 10,
    init_size: null,
    n_init: "auto",
    reassignment_ratio: 0.01,
  },
  spectral_clustering: {
    n_clusters: 8,
    eigen_solver: null,
    n_components: null,
    random_state: null,
    n_init: 10,
    gamma: 1.0,
    affinity: "rbf",
    n_neighbors: 10,
    eigen_tol: "auto",
    assign_labels: "kmeans",
    degree: 3,
    coef0: 1,
    kernel_params: null,
    n_jobs: null,
    verbose: false,
  },
};
