export const neuralModels = {
  multilayer_perceptron: {
    layers: { type: "array", default: [], description: "Array of { units: int, activation: str } objects" },
    learning_rate: { type: "float", default: 0.01, min: 0 },
    regularization: { type: "float", default: 0.1, min: 0 },
    optimizer: { type: ["adam", "sgd", "rmsprop"], default: "adam" },
    batch_size: { type: "int", default: 32, min: 1 },
    epochs: { type: "int", default: 100, min: 1 },
    activation: { type: ["relu", "tanh", "sigmoid"], default: "relu" },
    loss: { type: ["mse", "mae", "binary_crossentropy", "categorical_crossentropy"], default: "mse" },
    dropout_rate: { type: "float", default: 0.0, min: 0, max: 1.0 },
    momentum: { type: "float", default: 0.9, min: 0, max: 1.0 },
    early_stopping: { type: "bool", default: false },
    validation_split: { type: "float", default: 0.2, min: 0, max: 1.0 },
  },
  convolutional_neural_network: {
    layers: { type: "array", default: [], description: "Array of { units: int, activation: str, filters: int, kernel_size: int, pool_size: int } objects" },
    learning_rate: { type: "float", default: 0.01, min: 0 },
    regularization: { type: "float", default: 0.1, min: 0 },
    optimizer: { type: ["adam", "sgd", "rmsprop"], default: "adam" },
    batch_size: { type: "int", default: 32, min: 1 },
    epochs: { type: "int", default: 100, min: 1 },
    loss: { type: ["mse", "mae", "binary_crossentropy", "categorical_crossentropy"], default: "mse" },
    dropout_rate: { type: "float", default: 0.0, min: 0, max: 1.0 },
    momentum: { type: "float", default: 0.9, min: 0, max: 1.0 },
    filters: { type: "int", default: 32, min: 1 },
    kernel_size: { type: "int", default: 3, min: 1 },
    pool_size: { type: "int", default: 2, min: 1 },
    padding: { type: ["valid", "same"], default: "valid" },
    strides: { type: "int", default: 1, min: 1 },
    early_stopping: { type: "bool", default: false },
    validation_split: { type: "float", default: 0.2, min: 0, max: 1.0 },
  },
  recurrent_neural_network: {
    layers: { type: "array", default: [], description: "Array of { units: int, activation: str, return_sequences: bool } objects" },
    learning_rate: { type: "float", default: 0.01, min: 0 },
    regularization: { type: "float", default: 0.1, min: 0 },
    optimizer: { type: ["adam", "sgd", "rmsprop"], default: "adam" },
    batch_size: { type: "int", default: 32, min: 1 },
    epochs: { type: "int", default: 100, min: 1 },
    loss: { type: ["mse", "mae", "binary_crossentropy", "categorical_crossentropy"], default: "mse" },
    dropout_rate: { type: "float", default: 0.0, min: 0, max: 1.0 },
    momentum: { type: "float", default: 0.9, min: 0, max: 1.0 },
    rnn_type: { type: ["lstm", "gru", "simple"], default: "lstm" },
    return_sequences: { type: "bool", default: false },
    bidirectional: { type: "bool", default: false },
    early_stopping: { type: "bool", default: false },
    validation_split: { type: "float", default: 0.2, min: 0, max: 1.0 },
  },
};