export const regressionModels = {
  adaboost_regressor: {
    estimator: null,
    n_estimators: 50,
    learning_rate: 1.0,
    loss: "linear",
    random_state: null,
  },
  elastic_net: {
    alpha: 1.0,
    l1_ratio: 0.5,
    fit_intercept: true,
    precompute: false,
    max_iter: 1000,
    copy_X: true,
    tol: 0.0001,
    warm_start: false,
    positive: false,
    random_state: null,
    selection: "cyclic",
  },
  lasso: {
    alpha: 1.0,
    fit_intercept: true,
    precompute: false,
    copy_X: true,
    max_iter: 1000,
    tol: 0.0001,
    warm_start: false,
    positive: false,
    random_state: null,
    selection: "cyclic",
  },
  linear_regression: {
    fit_intercept: true,
    copy_X: true,
    n_jobs: null,
    positive: false,
  },
  ridge: {
    alpha: 1.0,
    fit_intercept: true,
    copy_X: true,
    max_iter: null,
    tol: 0.0001,
    solver: "auto",
    positive: false,
    random_state: null,
  },
  svr: {
    kernel: "rbf",
    degree: 3,
    gamma: "scale",
    coef0: 0.0,
    tol: 0.001,
    C: 1.0,
    epsilon: 0.1,
    shrinking: true,
    cache_size: 200,
    verbose: false,
    max_iter: -1,
  },
};
